{
  level: 'error',
  message: Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1138:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432
  },
  label: 'logs',
  timestamp: '2021-05-24T10:26:49.639Z'
}
{
  message: 'relation "product_review" already exists',
  length: 108,
  name: 'QueryFailedError',
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'heap.c',
  line: '1162',
  routine: 'heap_create_with_catalog',
  query: 'CREATE TABLE "product_review" ("userId" bigint NOT NULL, "productId" bigint NOT NULL, "rating" double precision NOT NULL, "message" text NOT NULL, "productCategoryId" integer, "productUserId" integer, CONSTRAINT "PK_031e4b7765b46b636078cbb27b8" PRIMARY KEY ("userId", "productId"))',
  parameters: [],
  level: 'error',
  label: 'logs',
  timestamp: '2021-05-26T10:37:54.474Z'
}
{
  message: 'relation "product_review" already exists',
  length: 108,
  name: 'QueryFailedError',
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'heap.c',
  line: '1162',
  routine: 'heap_create_with_catalog',
  query: 'CREATE TABLE "product_review" ("userId" bigint NOT NULL, "productId" bigint NOT NULL, "rating" double precision NOT NULL, "message" text NOT NULL, "productCategoryId" integer, "productUserId" integer, CONSTRAINT "PK_031e4b7765b46b636078cbb27b8" PRIMARY KEY ("userId", "productId"))',
  parameters: [],
  level: 'error',
  label: 'logs',
  timestamp: '2021-05-26T10:38:49.877Z'
}
{
  level: 'error',
  message: Error: connect EHOSTUNREACH 143.198.167.112:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1138:16) {
    errno: -4073,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '143.198.167.112',
    port: 5432
  },
  label: 'logs',
  timestamp: '2021-06-03T17:38:04.928Z'
}
{
  level: 'error',
  message: error: database "hustlers_db" does not exist
      at Parser.parseErrorMessage (C:\Users\casper-adams\Desktop\liredit\server\node_modules\pg-protocol\dist\parser.js:287:98)
      at Parser.handlePacket (C:\Users\casper-adams\Desktop\liredit\server\node_modules\pg-protocol\dist\parser.js:126:29)
      at Parser.parse (C:\Users\casper-adams\Desktop\liredit\server\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (C:\Users\casper-adams\Desktop\liredit\server\node_modules\pg-protocol\dist\index.js:11:42)
      at Socket.emit (node:events:369:20)
      at addChunk (node:internal/streams/readable:313:12)
      at readableAddChunk (node:internal/streams/readable:288:9)
      at Socket.Readable.push (node:internal/streams/readable:227:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 96,
    severity: 'FATAL',
    code: '3D000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postinit.c',
    line: '875',
    routine: 'InitPostgres'
  },
  label: 'logs',
  timestamp: '2021-06-03T22:41:23.760Z'
}
